name: zumpunzari
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eaeae8'
    - '#a4a5a0'
    - '#383836'
    - '#5d5d5b'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
